set(OUTPUT_DIRECTORY_ROOT "${CMAKE_CURRENT_BINARY_DIR}/bundle")
set(OUTPUT_DIRECTORY_RESOURCES "${OUTPUT_DIRECTORY_ROOT}")

file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY_ROOT}")
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY_RESOURCES}")

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${OUTPUT_DIRECTORY_ROOT}")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${OUTPUT_DIRECTORY_ROOT}")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${OUTPUT_DIRECTORY_ROOT}")